/**
 * The Red Brick Lettings portfolio as public listings.
 *
 * Source: `portfolio.json`, generated by `scripts/listings/extract-portfolio.py` from the
 * agency's own records (EPC certificates on the public GOV.UK register + the office
 * occupancy sheet). It carries ONLY public-safe facts — street name, postcode district,
 * property type, floor area, EPC rating and whether the home is currently let — never a
 * house number, flat letter, owner, tenant, contact, tenancy date or the rent of an
 * occupied home. Bedrooms, bathrooms and photographs are not published until confirmed
 * from a document (`null` → "to be confirmed"; placeholder image → "photographs to follow").
 *
 * The neighbourhood shown is the agency's best assignment of the street to a public area
 * name; the map pin is the area's approximate centre with a small deterministic offset,
 * never the home itself.
 */
import { areas, getArea } from "./areas";
import portfolio from "./portfolio.json";
import type { Listing, ListingStatus, PropertyType } from "./types";
import { propertyTypeLabels, propertyTypes } from "./types";

interface PortfolioRecord {
  readonly id: string;
  readonly slug: string;
  readonly street: string;
  readonly outwardPostcode: string | null;
  readonly propertyType: string | null;
  readonly epcPropertyType: string | null;
  readonly floorAreaSqM: number | null;
  readonly epcRating: string | null;
  readonly epcValidUntil: string | null;
  readonly status: string;
  readonly rentPcm: number | null;
}

/** Street → area key (Peterborough neighbourhoods; see areas.ts). Unlisted streets fall back to the district. */
const STREET_AREAS: Record<string, string> = {
  "Lincoln Road|PE1": "millfield",
  "Lincoln Road|PE4": "walton",
  "Scotney Street|PE1": "millfield",
  "Alma Road|PE1": "millfield",
  "St Paul's Road|PE1": "newengland",
  "Northfield Road|PE1": "newengland",
  "Francis Gardens|PE1": "eastfield",
  "Eastfield Road|PE1": "eastfield",
  "Elmfield Road|PE1": "eastfield",
  "Peveril Road|PE1": "eastfield",
  "Queens Drive|PE1": "eastfield",
  "Furze Ride|PE1": "dogsthorpe",
  "Field Walk|PE1": "dogsthorpe",
  "Eastern Avenue|PE1": "dogsthorpe",
  "Exeter Road|PE1": "dogsthorpe",
  "Rasen Court|PE1": "dogsthorpe",
  "Ratcliffe Court|PE1": "central",
  "Belsize Avenue|PE2": "woodston",
  "Oundle Road|PE2": "woodston",
  "Fellowes Gardens|PE2": "fletton",
  "Brudenell|PE2": "orton",
  "Holdich Street|PE3": "westtown",
  "Orme Road|PE3": "westtown",
  "Priory Road|PE3": "westtown",
  "Fulham Road|PE3": "netherton",
  "Nicholls Avenue|PE3": "netherton",
  "Wilton Drive|PE3": "netherton",
  "Almoners Lane|PE3": "longthorpe",
  "Clipston Walk|PE3": "bretton",
  "Bozeat Way|PE3": "bretton",
  "Everdon Way|PE3": "bretton",
  "Ellindon|PE3": "bretton",
  "Oxclose|PE3": "bretton",
  "Sandford|PE3": "bretton",
  "Uplands|PE4": "werrington",
  "Cranemore|PE4": "werrington",
};

const DISTRICT_FALLBACK: Record<string, string> = { PE1: "central", PE2: "fletton", PE3: "bretton", PE4: "werrington", PE7: "hampton" };

/** Deterministic small offset in [-0.004, 0.004] from the record id, so pins in one area do not stack. */
function jitter(seed: string, salt: number): number {
  let h = 2166136261 ^ salt;
  for (let i = 0; i < seed.length; i += 1) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return (((h >>> 0) % 8001) / 8000 - 0.5) * 0.008;
}

const generatedOn: string = portfolio.generatedOn;
const SOURCE = `EPC register (GOV.UK certificate) and Red Brick occupancy records, checked ${generatedOn.split("-").reverse().join("/")}`;

function toListing(r: PortfolioRecord): Listing {
  const outward = r.outwardPostcode ?? "PE";
  const areaKey = STREET_AREAS[`${r.street}|${outward}`] ?? DISTRICT_FALLBACK[outward] ?? "central";
  const area = getArea(areaKey) ?? areas[0]!;
  const type: PropertyType = (propertyTypes as readonly string[]).includes(r.propertyType ?? "") ? (r.propertyType as PropertyType) : "terraced-house";
  const status: ListingStatus = r.status === "available" ? "available" : "let";
  const typeLabel = propertyTypeLabels[type];
  const title = `${typeLabel} on ${r.street}`;
  const epcValid = r.epcRating && r.epcValidUntil && r.epcValidUntil >= generatedOn;
  const features = [
    r.floorAreaSqM ? `About ${r.floorAreaSqM} m² floor area (EPC)` : null,
    epcValid ? `EPC rating ${r.epcRating}` : null,
    r.epcPropertyType ? `${r.epcPropertyType} (EPC register)` : null,
    "Managed by Red Brick Lettings",
  ].filter((f): f is string => Boolean(f));
  const summary =
    status === "available"
      ? `A ${typeLabel.toLowerCase()} on ${r.street} in ${area.name}, Peterborough (${outward}), available to rent through Red Brick Lettings.`
      : `A ${typeLabel.toLowerCase()} on ${r.street} in ${area.name}, Peterborough (${outward}), part of the Red Brick Lettings managed portfolio and currently let.`;
  const description =
    status === "available"
      ? `This home is available now. Ask us about a viewing and we will confirm the rent, deposit, bedrooms and what is included before you commit to anything. Photographs and full details follow once approved.`
      : `This home is currently let, so it is not available to view. It is shown so you can see the kind of homes we manage across Peterborough. If you would like to hear when a similar home becomes available, ask us and we will keep you posted. Photographs and full details are published only when a home is being marketed.`;
  return {
    id: r.id,
    slug: r.slug,
    title,
    summary,
    description,
    demoOnly: false,
    source: SOURCE,
    status,
    availableFrom: null,
    location: {
      area: area.key,
      outwardPostcode: outward,
      approximateLatitude: area.approximateLatitude + jitter(r.id, 1),
      approximateLongitude: area.approximateLongitude + jitter(r.id, 2),
    },
    property: {
      type,
      bedrooms: null,
      bathrooms: null,
      receptionRooms: null,
      furnishing: null,
      sizeSqM: r.floorAreaSqM,
    },
    pricing: {
      rentPcm: status === "available" ? r.rentPcm : null,
      deposit: null,
      holdingDeposit: null,
      billsIncluded: false,
    },
    councilTaxBand: null,
    epcRating: epcValid ? { value: r.epcRating!, verifiedOn: generatedOn, source: "EPC register (GOV.UK certificate)" } : null,
    features,
    media: { cover: { kind: "placeholder", alt: `Placeholder illustration for a ${typeLabel.toLowerCase()} — photographs to follow` } },
  };
}

/** The portfolio as listings, in source order (the repository sorts for display). */
export const portfolioListings: readonly Listing[] = (portfolio.properties as PortfolioRecord[]).map(toListing);

/** For the honesty line on the properties page. */
export const portfolioGeneratedOn = generatedOn;
